export const commandIds = [
  "lazy-open",
  "new-tab",
  "duplicate-current",
  "toggle-pin-current",
  "toggle-mute-current",
  "reload-current",
  "go-back",
  "go-forward",
  "previous-tab",
  "next-tab",
  "move-tab-left",
  "move-tab-right",
  "move-tab-to-new-window",
  "close-current",
  "close-other-tabs",
  "close-tabs-to-right",
  "suspend-current",
  "suspend-others",
  "wake-first",
  "zoom-in",
  "zoom-out",
  "zoom-reset",
  "new-window",
  "focus-next-window",
  "minimize-window",
  "maximize-window",
  "toggle-fullscreen-window",
  "close-window",
  "scroll-top",
  "scroll-bottom",
  "page-up",
  "page-down",
  "open-downloads",
  "open-history",
  "open-bookmarks",
  "open-settings",
  "open-extensions",
  "open-shortcuts",
  "reload-extension",
] as const;

export type CommandId = (typeof commandIds)[number];
